session_name: rc-config
windows:
- focus: 'true'
  layout: ad5b,204x48,0,0[204x33,0,0,0,204x14,0,34,1]
  options: {}
  panes:
  - focus: 'true'
    shell_command: nvim
  - gst
  start_directory: ~/.dotfiles
  window_name: nvim
