
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here

# Clipboard history manager (cliphist + wofi)
bind = Super, V, exec, pkill -x wofi || ~/.config/hypr/scripts/cliphist.sh c
bind = Super+Shift, V, exec, pkill -x wofi || ~/.config/hypr/scripts/cliphist.sh d
bind = Super+Ctrl, V, exec, ~/.config/hypr/scripts/cliphist.sh w
