
# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

# See https://wiki.hyprland.org/Configuring/Window-Rules/

windowrule = opacity 0.90 0.90, class:^(firefox)$
windowrule = opacity 0.90 0.90, class:^(Brave-browser)$
windowrule = opacity 0.80 0.80, class:^(code-oss)$
windowrule = opacity 0.80 0.80, class:^(Code)$
windowrule = opacity 0.80 0.80, class:^(code-url-handler)$
windowrule = opacity 0.80 0.80, class:^(code-insiders-url-handler)$
windowrule = opacity 0.80 0.80, class:^(ghostty)$
windowrule = opacity 0.80 0.80, class:^(kitty)$
windowrule = opacity 0.80 0.80, class:^(org.kde.dolphin)$

windowrule = float on, class:^(org.kde.dolphin)$, title:^(Progress Dialog — Dolphin)$
windowrule = float on, class:^(org.kde.dolphin)$, title:^(Copying — Dolphin)$
windowrule = float on, class:^(firefox)$, title:^(Picture-in-Picture)$
windowrule = float on, class:^(firefox)$, title:^(Library)$
windowrule = float on, class:^(vlc)$

# Dialogs and modals
windowrule = float on, title:^(Open)$
windowrule = float on, title:^(Choose Files)$
windowrule = float on, title:^(Save As)$
windowrule = float on, title:^(Confirm to replace files)$
windowrule = float on, title:^(File Operation Progress)$

# Layer rules
layerrule = blur, namespace:wofi
layerrule = ignore_alpha 0, namespace:wofi
layerrule = blur, namespace:notifications
layerrule = ignore_alpha 0, namespace:notifications
layerrule = blur, namespace:waybar
layerrule = ignore_alpha 0, namespace:waybar
layerrule = blur, namespace:logout_dialog
