
# █▀▀ █░█ █▀█ █▀ █▀█ █▀█
# █▄▄ █▄█ █▀▄ ▄█ █▄█ █▀▄

# Use default cursor -- no theme needed
# exec = hyprctl setcursor Bibata-Modern-Ice 20

# Font settings
exec = gsettings set org.gnome.desktop.interface font-name 'JetBrains Mono Nerd Font 10'
exec = gsettings set org.gnome.desktop.interface document-font-name 'JetBrains Mono Nerd Font 10'
exec = gsettings set org.gnome.desktop.interface monospace-font-name 'JetBrains Mono Nerd Font 10'
exec = gsettings set org.gnome.desktop.interface font-antialiasing 'rgba'
exec = gsettings set org.gnome.desktop.interface font-hinting 'full'


# █▀ █▀█ █▀▀ █▀▀ █ ▄▀█ █░░
# ▄█ █▀▀ ██▄ █▄▄ █ █▀█ █▄▄

decoration {
    dim_special = 0.3
    blur {
        special = true
    }
}
