# Catppuccin Mocha theme for Kitty
include themes/Catppuccin-Mocha.conf

background_opacity 0.85
background_blur 12
cursor_shape block
cursor_blink_interval 0
font_family JetBrainsMonoNL Nerd Font
font_size 12
