[General]
initialize_flag=1
random_key="pA/0e/j1Y2h3yTLU6qpM5h/1dvQCO9lJMSZ8mNQmsoI="
zkp1amlgq8ekvdbvgajt8g%40xmpp.zoom.us.asyn.enc.db=1
zkp1amlgq8ekvdbvgajt8g%40xmpp.zoom.us.enc.db=1
zkp1amlgq8ekvdbvgajt8g%40xmpp.zoom.us.idx.enc.db=1
zkp1amlgq8ekvdbvgajt8g%40xmpp.zoom.us.sync.enc.db=1
