[General]
%2B8gcPZIuASRcihpYJW6UA83rPnH%2B7ifu11s9xp3p8Rc%23=1728908183
63tJmSFEpYg9dR34FZPBHK8VKGPcUT1yDVJWSS9UTuU%23=1728908183
GeoLocale=system
N65z0ERhK0hfZOUrpvZbKa20IAIu0Etuq8T%2BuqWl%2Bkw%23=1728908183
SensitiveInfoMaskOn=true
UeJ7AgrtBappnQjaaFui4jk8yVCY2K4zE14gyE34Rzo%23=1728908183
autoPlayGif=false
autoScale=true
bForceMaximizeWM=false
captureHDCamera=true
cefInstanceCountLimit=-1
cefRefreshTime=0
chatListPanelLastWidth=230
com.zoom.client.langid=0
conf.webserver=https://zoom.us
currentMeetingId=3866903909
deviceID=14:C2:13:0F:EA:7E
disableCef=false
enable.host.auto.grab=true
enableAlphaBuffer=true
enableCefGpu=false
enableCefLog=false
enableCloudSwitch=true
enableLog=true
enableMiniWindow=true
enableQmlCache=true
enableScreenSaveGuard=false
enableStartMeetingWithRoomSystem=false
enableTestMode=false
enablegpucomputeutilization=false
fake.version=
flashChatTime=0
forceEnableTrayIcon=true
forceSSOURL=
host.auto.grab.interval=10
isTransCoding=false
jK9BkbV8zNjw7whdX9AnddbmbOu4N8hVKwVt8iDnC38%23=1728908183
logLevel=info
newMeetingWithVideo=true
noSandbox=false
pOoALJyX%2BqjXWD3Cr1Q4lH5ZpVshFjYob0SH3xBr2jQ%23=1728908183
playSoundForNewMessage=false
rbN4avm02r1FyFexbDXLliM5BlEubOBVnjnYbA%2BuL1c%23=1728908183
shareBarTopMargin=0
showOneTimePTAICTipHubble=false
showOneTimeQAMostUpvoteHubble=true
showOneTimeQueriesOptionTip=true
showOneTimeTranslationUpSellTip=false
showSystemTitlebar=false
speaker_volume=255
sso_domain=.zoom.us
sso_gov_domain=.zoomgov.com
system.audio.type=default
timeFormat12HoursEnable=true
translationFreeTrialTipShowTime=0
upcoming_meeting_header_image=
useSystemTheme=false
userEmailAddress=mjonyh-phy@sust.edu
xwayland=true

[1VGa6fEsTQYEquYOdMv]
j1V5NQSTWNQPlSB8TSaIgvM%23=1728908183

[AS]
showframewindow=true

[AvZU7w7xMRB%2BbJ0zur6vx0J]
v0JQVMs8tUQjFO4She0%23=1728908183

[YF]
0eWmMbhXv8dLkLuwpAohJHPqqY98tsvJ8RMNR5r0%23=1728908183

[ZfyNXsYVXn89sSD]
u%2BfYJObfh7c2x33NhQnPBCxnUKg%23=1728908183

[p2j01nOS5WVbsNRvQFnMTmH5SbwLdPoVQxAt]
B0jJHc%23=1728908183

[pvKc9SrvNy]
UrM6djKC7sBYYhjF2xNCSHVpXDpFealQ%23=1728908183
